unit Unit2;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, Menus;

type
  TTest1 = class(TForm)
    lbl1: TLabel;
    btnSTART: TButton;
    btnFINISH: TButton;
    btnNAZAD: TButton;
    btnVPERED: TButton;
    rb1: TRadioButton;
    rb2: TRadioButton;
    rb3: TRadioButton;
    mm1: TMainMenu;
    N1: TMenuItem;
    lbl2: TLabel;
    lbl3: TLabel;
    lbl4: TLabel;
    procedure btnSTARTClick(Sender: TObject);
    procedure btnVPEREDClick(Sender: TObject);
    procedure btnNAZADClick(Sender: TObject);
    procedure N1Click(Sender: TObject);
    procedure btnFINISHClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  otv:string;
  Test1: TTest1;
  k,m:string;
  f,t:Text;
  i,j,ns_pol,ns_otr,ns,vd_pol,vd_otr,vd,nz_pol,nz_otr,nz,c: integer;
  mas:array[1..30] of Integer;

implementation

uses Unit1;

{$R *.dfm}

procedure TTest1.btnSTARTClick(Sender: TObject);
begin
  lbl1.Show;
  lbl4.Hide;
  rb1.Show;
  rb2.Show;
  rb3.Show;
  btnVPERED.Show;
  i:=1;
  AssignFile(f,'Тесты\Тест 1\Вопросы\1.txt');
  Reset(f);
  Readln(f,otv);
  lbl1.Caption:=otv;
  Readln(f,otv);
  rb1.Caption:=otv;
  Readln(f,otv);
  rb2.Caption:=otv;
  Readln(f,otv);
  rb3.Caption:=otv;
  btnSTART.Visible:=False;
end;

procedure TTest1.btnVPEREDClick(Sender: TObject);
begin
c:=0;
if rb1.Checked then begin mas[i]:=1;
                          rb1.Checked:=False;
                          c:=1;end;
if rb2.Checked then begin mas[i]:=2;
                          rb2.Checked:=False;
                          c:=1;end;
if rb3.Checked then begin mas[i]:=3;
                          rb3.Checked:=False;
                          c:=1;end;
if c=1 then begin
i:=i+1;
btnNAZAD.Show;
AssignFile(f,'Тесты\Тест 1\Вопросы\'+InttoStr(i)+'.txt');
Reset(f);
Readln(f,otv);
lbl1.Caption:=otv;
Readln(f,otv);
rb1.Caption:=otv;
Readln(f,otv);
rb2.Caption:=otv;
Readln(f,otv);
rb3.Caption:=otv;
if i=30 then begin btnVPERED.visible:=false;
                   btnFINISH.visible:=true;end;end
else showmessage('Нужно выбрать хотя бы один вариант');end;
procedure TTest1.btnNAZADClick(Sender: TObject);
begin i:=i-1;
  btnFINISH.Hide;
  btnVPERED.Show;
  if i=1 then btnNAZAD.Hide;
  AssignFile(f,'Тесты\Тест 1\Вопросы\'+InttoStr(i)+'.txt');
  Reset(f);
  Readln(f,otv);
  lbl1.Caption:=otv;
  Readln(f,otv);
  rb1.Caption:=otv;
  Readln(f,otv);
  rb2.Caption:=otv;
  Readln(f,otv);
  rb3.Caption:=otv;
end;

procedure TTest1.N1Click(Sender: TObject);
begin Test1.Close;
      Menushka.show; end;

procedure TTest1.btnFINISHClick(Sender: TObject);
begin c:=0;
if rb1.Checked then begin mas[i]:=1;
                          rb1.Checked:=False;
                          c:=1;end;
if rb2.Checked then begin mas[i]:=2;
                          rb2.Checked:=False;
                          c:=1;end;
if rb3.Checked then begin mas[i]:=3;
                          rb3.Checked:=False;
                          c:=1;end;
if c=1 then begin ns_pol:=0;
                  ns_otr:=0;
                  ns:=0;
                  vd_pol:=0;
                  vd_otr:=0;
                  vd:=0;
                  nz_pol:=0;
                  nz_otr:=0;
                  nz:=0;
                  rb1.Hide;
                  rb2.Hide;
                  rb3.Hide;
                  lbl1.Hide;
                  btnNAZAD.Hide;
for j:=1 to 30 do begin case j of 1:  begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  2:  begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  3:  begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  4:  begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  5:  begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  6:  begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  7:  begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  8:  begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  9:  begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  10: begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  11: begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  12: begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  13: begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  14: begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  15: begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  16: begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  17: begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  18: begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  19: begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  20: begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  21: begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  22: begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  23: begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  24: begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  25: begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  26: begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  27: begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  28: begin case mas[j] of 2: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  29: begin case mas[j] of 1: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           3: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;
                                  30: begin case mas[j] of 3: begin ns_pol:=ns_pol+1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_otr:=nz_otr-1;end;
                                                           2: begin ns_otr:=ns_otr-1;
                                                                    vd_otr:=vd_otr-1;
                                                                    nz_pol:=nz_pol+1;end;
                                                           1: begin ns_otr:=ns_otr-1;
                                                                    vd_pol:=vd_pol+1;
                                                                    nz_otr:=nz_otr-1;end;end;end;end;end;
lbl1.Hide;
btnFINISH.Hide;
btnNAZAD.Hide;
lbl2.Show;
lbl3.Show;
user:=menushka.lbl3.Caption;
if user='Гость' then fuser[1]:=1
else suser[1]:=1;
ns:=ns_pol+ns_otr+30;
vd:=vd_pol+vd_otr+30;
nz:=nz_pol+nz_otr+30;
AssignFile(t,'Userы/'+user+'/Тест 1.txt');
if (ns>vd) and (ns>nz) then begin AssignFile(f,'Тесты\Тест 1\Результаты\1.txt');
                                  Reset(f);
                                  Readln(f,otv);
                                  lbl2.Caption:=otv;
                                  Rewrite(t);
                                  Writeln(t,'На себя');
                                  Readln(f,otv);
                                  lbl3.Caption:=otv;
                                  end;
if (vd>ns) and (vd>nz) then begin AssignFile(f,'Тесты\Тест 1\Результаты\2.txt');
                                  Reset(f);
                                  Readln(f,otv);
                                  lbl2.Caption:=otv;
                                  Rewrite(t);
                                  Writeln(t,'На общение');
                                  Readln(f,otv);
                                  lbl3.Caption:=otv;end;
if (nz>ns) and (nz>vd) then begin AssignFile(f,'Тесты\Тест 1\Результаты\3.txt');
                                  Reset(f);
                                  Readln(f,otv);
                                  lbl2.Caption:=otv;
                                  Rewrite(t);
                                  Writeln(t,'На дело');
                                  Readln(f,otv);
                                  lbl3.Caption:=otv;end;end
            else showmessage('Нужно выбрать хотя бы один вариант');
            closefile(t);end;
end.
